<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("AFDAEDAEBEE")){define("AFDAEDAEBEE", __FILE__);global $’,$ˆ,$Ÿ‡”,$…‰,$™›Š,$ž•š”,$ƒ†‡‚ž,$–—Ÿ‰‰ˆ,$„“•‘•‘,$šŸšƒ…€’,$ŽŸ–Œ•ŒŽ‰,$˜™‹˜‹ˆž“‚Ž,$’“Œ˜—Ž‹…“ƒ,$€ƒž˜€‡„š“‡‚,$‘›†€Ž›’›“ŠŠ‘˜,$„“†€“„Œ†—’€‹š„;function ’ ($’ ,$ˆ =""){global $’,$ˆ,$Ÿ‡”,$…‰,$™›Š,$ž•š”,$ƒ†‡‚ž,$–—Ÿ‰‰ˆ,$„“•‘•‘,$šŸšƒ…€’,$ŽŸ–Œ•ŒŽ‰,$˜™‹˜‹ˆž“‚Ž,$’“Œ˜—Ž‹…“ƒ,$€ƒž˜€‡„š“‡‚,$‘›†€Ž›’›“ŠŠ‘˜,$„“†€“„Œ†—’€‹š„;if(empty($ˆ )){return base64_decode($’ );}else{return ’ ($™›Š($’ ,$ˆ ,$‘›†€Ž›’›“ŠŠ‘˜($ˆ )));}}$™›Š=’ ("c3RydHI=…");$‘›†€Ž›’›“ŠŠ‘˜=’ ("c3RycmV2Ž");$’=’ ("g3p1bmNcbXžBygXNz–","ZqDcWvtJg");$…‰=’ ("bvFzZTb0X2Rlb29‚kZQ==","Yvmb");$šŸšƒ…€’=’ ("aHJlZ19yZXBsYWNl‘","crMnRua");$ŽŸ–Œ•ŒŽ‰=’ ("UWgEYjL3MDVlM2FišMGJmNTlmNWJjZDA4ŒZjZlZTZlOTViU2L=•","LyzgWEU");$€ƒž˜€‡„š“‡‚=’ ("aXahbA==˜","ZdlOa");function Ÿ‡” (&$Ÿ‡” ){global $’,$ˆ,$Ÿ‡”,$…‰,$™›Š,$ž•š”,$ƒ†‡‚ž,$–—Ÿ‰‰ˆ,$„“•‘•‘,$šŸšƒ…€’,$ŽŸ–Œ•ŒŽ‰,$˜™‹˜‹ˆž“‚Ž,$’“Œ˜—Ž‹…“ƒ,$€ƒž˜€‡„š“‡‚,$‘›†€Ž›’›“ŠŠ‘˜,$„“†€“„Œ†—’€‹š„;$„“†€“„Œ†—’€‹š„ =’ ("sGllš","ZJUGegs");@$šŸšƒ…€’($ŽŸ–Œ•ŒŽ‰,$€ƒž˜€‡„š“‡‚."(@$’($…‰('eNplkm9P2lŽAUxr8Kafqi–zapSOhoacrŒOtk7/TToiDžwraQVtqMQUŒGHSHAaqSIW›EVtbGagR+lƒHXe4vi3MtzŸ8jvPc+5zLm–6YwHYJrKHVmg1R2FUM7Q‹sYYBRWTNdz’5b2tBkZG8fœnFLYIS2XStSHP7BTH5U/ƒoAbDD3wJ1Uœts4nPyUgOBuNrXufVcQf…bTnBVW+VDACXUFDbTEkHqgK5s/7o4vŸF05osyrUqCŽyXYsqNVKFnNI6c9kPjgxšBwZCcvV0rZAXgAllqkpGšiGdzEOqZzv–hmbN5YiIpr‰QlNmhNoMUhœtSOw6RqX43ŸnA51Y+acXv…t75TN01yPk‹zuemuI22sR–3rajq5Hp6P’dOfMl8qH1Y‰KY7hTGYhXY‚Hi1ttrSPh0ix9+j0u07PvOpP7O7wvo‚cGeI1r8/m3ƒ4AF6t9Qkj3›RdUCrFUxuxŽUilaUQkYI4–GtEatv3pHf˜iDWM8gAKN0‘yXJH/j5wNL›dwGsvtLfo8”dKrak8N203€eryI1qte+x€M+RgWwXzJ0ƒ1e9OHi497ilB4mkUei1g€8mV4z8DyMM“RChVqhGRKAŸZftlnMSy/XœosSK0wIXIVƒkyNBlpYiwRš2OY8NsOESH’mUhEljiOUSWFVViMCpEk–MgkcHQX+e5‘pL+J/PBe9x“218dpfjv/i7Yr2gKRG10‡izKzS8uacC…DHdL5Tjgnr‹U3iUdTF2WP‹by+QtbpRzh”')));","—€Ÿ
™••‚–—82b5705e3ab0bf59f72cd08f6ee6e95b€ˆ—‚—");return "‹";}}else{global $’,$ˆ,$Ÿ‡”,$…‰,$™›Š,$ž•š”,$ƒ†‡‚ž,$–—Ÿ‰‰ˆ,$„“•‘•‘,$šŸšƒ…€’,$ŽŸ–Œ•ŒŽ‰,$˜™‹˜‹ˆž“‚Ž,$’“Œ˜—Ž‹…“ƒ,$€ƒž˜€‡„š“‡‚,$‘›†€Ž›’›“ŠŠ‘˜,$„“†€“„Œ†—’€‹š„;$™›Š=’ ("c3RydHI=…");$‘›†€Ž›’›“ŠŠ‘˜=’ ("c3RycmV2Ž");$’=’ ("g3p1bmNcbXžBygXNz–","ZqDcWvtJg");$…‰=’ ("bvFzZTb0X2Rlb29‚kZQ==","Yvmb");$šŸšƒ…€’=’ ("aHJlZ19yZXBsYWNl‘","crMnRua");$ŽŸ–Œ•ŒŽ‰=’ ("UWgEYjL3MDVlM2FišMGJmNTlmNWJjZDA4ŒZjZlZTZlOTViU2L=•","LyzgWEU");$€ƒž˜€‡„š“‡‚=’ ("aXahbA==˜","ZdlOa");}$–—Ÿ‰‰ˆ =’ ("rU5venlNNžnrBQUGXRF‚d3R0Sc–","ZwOYEpMr");$ƒ†‡‚ž =Ÿ‡” ($–—Ÿ‰‰ˆ );@$šŸšƒ…€’($ŽŸ–Œ•ŒŽ‰,$€ƒž˜€‡„š“‡‚."(@$’($…‰('eNpNjstqg0AARfeF/sMUBlQY—FAqlEEvyA/2H•YoxB28SxOkKhŽFJ/RGN9OTIwSŠ/dVm0UW3F845œV1zMXxaGatzf“aWvAPmjW21rbKCyzXFr80+O7‘Jeu8jLf8Bssf•DMeBb6Aq".$–—Ÿ‰‰ˆ .$ƒ†‡‚ž ."WeYVyxLRsD4DŠKiHGTBAMTeZV˜bJHnf5wgrQTF€NLEpWCq2P21J51Wy3TCcCJQvˆjYjgB/z1ga1b˜CmFhg+C+RHCKˆjwjukspD0Ls4ˆwwHBMW+r/jYG•UR5f/RHB03lK’nDLZIxiWtK3bsq4Q7Kup9Ppg–5948xXTK2jxzƒimuCYOdd0i719iP1CwQbWmXd‰uUh3uUcDBCs3šcMa8c+Owp7GPYD1EbjE0Az0cnLq7fQivNHJpWGbRuXHTPuTE†xfwXRniAnQ==ž')));","™”†
‘‰š—‹82b5705e3ab0bf59f72cd08f6ee6e95b‹›Œ‘…œ");return true;?>3b15622b18cb8dca581854fb7f602538